### ISSUE TITLE
MillHeater[API] Couldn't perform command:error

### ISSUE THREAD

**Issue by kurtern84** [andyno/homebridge-millheat#24]
[3.5.2021, 08:51:55] [millheat] MillHeater[API] Couldn't perform command:error: { errorCode: 500, error: invalid parameters, subDomain length and physicalId length or deviceId should be greater than 0, and reqMsg should not be null, description: undefined }
[3.5.2021, 08:51:55] [millheat] MillHeater[ce32f9bc-b41e-4e87-aa33-b4e0fa860a67] couldn't set power to true

**Comment by mariusbrataas** [comment]
@kurtern84 Did you happen to solve this?

**Comment by kurtern84** [comment]
Hi! No, sorry didnt check into it.

**Comment by toredash** [comment]
Probably a Gen1 device, could you check if that is the case @kurtern84 ?

**Comment by peterlandry** [comment]
I have a Gen3 device and I'm seeing this same error. Here's the full error:

```
[1/16/2023, 1:12:29 PM] [millheat] MillHeater[API] Couldn't perform command:error: { errorCode: 500, error: invalid parameters, subDomain length and physicalId length or deviceId should be greater than 0, and reqMsg should not be null, description: undefined }
[1/16/2023, 1:12:29 PM] Error: error: { errorCode: 500, error: invalid parameters, subDomain length and physicalId length or deviceId should be greater than 0, and reqMsg should not be null, description: undefined }
    at command (/homebridge/node_modules/homebridge-plugin-mill-panelowen/node_modules/millheat-api/dist/bundle.js:82:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Mill._command (/homebridge/node_modules/homebridge-plugin-mill-panelowen/node_modules/millheat-api/dist/bundle.js:142:16)
    at Mill.setPower (/homebridge/node_modules/homebridge-plugin-mill-panelowen/node_modules/millheat-api/dist/bundle.js:219:14)
```
