### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by brodyhoskins** [andyno/homebridge-millheat#3]
I am receiving the following error:

```bash
(node:25956) UnhandledPromiseRejectionWarning: ReferenceError: device is not defined
    at MillPlatform.getAllHeaters (/usr/local/lib/node_modules/homebridge-millheat/src/platform.js:39:52)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:25956) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25956) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by andyno** [comment]
Should be fixed now
