### ISSUE TITLE
Error: The requested platform 'millheat' was not registered by any plugin.

### ISSUE THREAD

**Issue by eiriklw** [andyno/homebridge-millheat#8]
Hva gjør jeg feil her?

Error: The requested platform 'millheat' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (C:\Users\eirik\AppData\Roaming\npm\node_modules\homebridge\src\pluginManager.ts:224:15)
    at C:\Users\eirik\AppData\Roaming\npm\node_modules\homebridge\src\server.ts:387:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (C:\Users\eirik\AppData\Roaming\npm\node_modules\homebridge\src\server.ts:374:27)
    at Server.start (C:\Users\eirik\AppData\Roaming\npm\node_modules\homebridge\src\server.ts:153:29)
    at cli (C:\Users\eirik\AppData\Roaming\npm\node_modules\homebridge\src\cli.ts:80:10)
    at Object.<anonymous> (C:\Users\eirik\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)

**Comment by vegargrim** [comment]
Fant du en løsning? Fikk samme problemet etter jeg oppdaterte

**Comment by paalolav** [comment]
Samme problem her.

**Comment by eiriklw** [comment]
> Fant du en løsning? Fikk samme problemet etter jeg oppdaterte

Fant ingen løsning nei

**Comment by paalolav** [comment]
Avinstallerte her og ventar nokre dagar. Vi kan jo evt kompilere forrige build.

**Comment by kims89** [comment]
Kjørte forrige build (1.0.4). Fungerte fint selv med nyeste versjon av homebridge som jeg har (1.1.3)

**Comment by eiriklw** [comment]
> Kjørte forrige build (1.0.4). Fungerte fint selv med nyeste versjon av homebridge som jeg har (1.1.3)

Gjorde det samme uten problemer. Må være noe i den nyeste builden

**Comment by andyno** [comment]
Det hadde sneket seg inn en bug pga. oppdateringer av noen avhengigheter. Tror det skal være fikset nå så dere kan teste nyeste versjon (1.0.6)

**Comment by eiriklw** [comment]
> Det hadde sneket seg inn en bug pga. oppdateringer av noen avhengigheter. Tror det skal være fikset nå så dere kan teste nyeste versjon (1.0.6)

Funket for meg!
